export namespace GLOBALENUMS {
  export enum DROPDOWNDATA {
    EXTERNAL_PARTNERS = 'EXTERNAL_PARTNERS',
  }
  export enum PROCESSMAPNODETYPE {
    PROCESSGROUP = 'PROCESSGROUP',
    PROCESS = 'PROCESS',
  }
}
