export namespace GLOBALENUMS {
  export enum DROPDOWNDATA {
    EXTERNAL_PARTNERS = 'EXTERNAL_PARTNERS',
    LOCATIONS = 'LOCATIONS',
    NODE_TYPES = 'NODE_TYPES',
    ORG_UNITS = 'ORG_UNITS',
    ORG_UNITS_AND_STAFF_POSITIONS = 'ORG_UNITS_AND_STAFF_POSITIONS',
    PROCESS_GROUPS = 'PROCESS_GROUPS',
    PROCESSES = 'PROCESSES',
    PROCESSES_DONE = 'PROCESSES_DONE',
    PROCESSES_UNDONE = 'PROCESSES_UNDONE',
    PROCESSGROUPS_AND_DONE_PROCESSES = 'PROCESSGROUPS_AND_DONE_PROCESSES',
    REQUIREMENT_CHAPTERS = 'REQUIREMENT_CHAPTERS',
    REQUIREMENTS = 'REQUIREMENTS',
    RESOURCEGROUPS = 'RESOURCEGROUPS',
    RESOURCES = 'RESOURCES',
    ROLES = 'ROLES',
    STAFF_POSITIONS = 'STAFF_POSITIONS',
    WORKING_GROUPS = 'WORKING_GROUPS',
    STATUS = 'STATUS',
  }
  export enum PROCESSMAPNODETYPE {
    PROCESSGROUP = 'PROCESSGROUP',
    PROCESS = 'PROCESS',
    CONTAINER = 'CONTAINER',
    PICTURE = 'PICTURE',
    TEXT = 'TEXT',
  }
}
